// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhcmGrgHzw1vV0FnDt6UxNxhiYgCiRGdo',
    appId: '1:790107190753:web:1c861cfc520bb4fc790ea0',
    messagingSenderId: '790107190753',
    projectId: 'devmob-edulycee',
    authDomain: 'devmob-edulycee.firebaseapp.com',
    storageBucket: 'devmob-edulycee.firebasestorage.app',
    measurementId: 'G-9FFP2P13H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJcmj92KdhEMGUoud4M2TTYFMgpIj4in4',
    appId: '1:790107190753:android:aa1d9ed01343fbd5790ea0',
    messagingSenderId: '790107190753',
    projectId: 'devmob-edulycee',
    storageBucket: 'devmob-edulycee.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhcmGrgHzw1vV0FnDt6UxNxhiYgCiRGdo',
    appId: '1:790107190753:web:0f1ac7b8939b2e42790ea0',
    messagingSenderId: '790107190753',
    projectId: 'devmob-edulycee',
    authDomain: 'devmob-edulycee.firebaseapp.com',
    storageBucket: 'devmob-edulycee.firebasestorage.app',
    measurementId: 'G-2QPDH04Z40',
  );
}
